# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c38d2d1551535a8fcd3c2b4e901ca835c9432997a29dcb7e8fed9041b24042e6f56645adc0f104257ddbb51e5ba72a2219fb87da9a054d25a2422609f5166f

test:
  secret_key_base: bac8d7a6270296646a089a08972866501a048c6c84e7c7e53f0140c317f6f0693113ccc6f2013f720dd187fc8b0cc70aabf704dbcfb2c2bcd0813c350ed841d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
